### ISSUE TITLE
[1pt] Create app and install basic dependencies - Setup (group task)

### ISSUE THREAD

**Issue by joseheco** [joseheco/space-travel#91]
- Create React App.
- Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).

**Comment by gabyse1** [comment]
We created react app, and installed redux dependencies successfully.

**Comment by joseheco** [comment]
Great start linter works fine !
